<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Voidwell.DaybreakGames.CensusStore\Voidwell.DaybreakGames.CensusStore.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Data\Voidwell.DaybreakGames.Data.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Domain\Voidwell.DaybreakGames.Domain.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Services\Voidwell.DaybreakGames.Services.csproj" />
  </ItemGroup>

</Project>
