<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AsyncKeyedLock" Version="8.1.2" />
    <PackageVersion Include="AutoMapper" Version="16.2.0" />
    <PackageVersion Include="DaybreakGames.Census" Version="10.0.0" />
    <PackageVersion Include="FlexLabs.EntityFrameworkCore.Upsert" Version="10.1.0" />
    <PackageVersion Include="FluentAssertions" Version="8.11.0" />
    <PackageVersion Include="IdentityModel" Version="7.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.SyndicationFeed.ReaderWriter" Version="1.0.2" />
    <PackageVersion Include="Moq" Version="4.21.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Voidwell.Common.Authentication" Version="1.0.2" />
    <PackageVersion Include="Voidwell.Common.Cache" Version="1.0.2" />
    <PackageVersion Include="Voidwell.Common.Logging" Version="1.0.2" />
    <PackageVersion Include="Voidwell.Common.Swagger" Version="1.0.2" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
