<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Voidwell.DaybreakGames.Census\Voidwell.DaybreakGames.Census.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Data\Voidwell.DaybreakGames.Data.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Utils\Voidwell.DaybreakGames.Utils.csproj" />
  </ItemGroup>

</Project>
