<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voidwell.DaybreakGames.Live\Voidwell.DaybreakGames.Live.csproj" />
    <ProjectReference Include="..\..\src\Voidwell.DaybreakGames.Services\Voidwell.DaybreakGames.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="MapTests\TestData\FacilityLinks.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MapTests\TestData\MapOwnership.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MapTests\TestData\MapRegions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
