<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>Voidwell.DaybreakGames.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Voidwell.DaybreakGames.Data\Voidwell.DaybreakGames.Data.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Services\Voidwell.DaybreakGames.Services.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Live\Voidwell.DaybreakGames.Live.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Voidwell.Common.Authentication" />
    <PackageReference Include="Voidwell.Common.Cache" />
    <PackageReference Include="Voidwell.Common.Logging" />
    <PackageReference Include="Voidwell.Common.Swagger" />
  </ItemGroup>

</Project>
