<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AsyncKeyedLock" />
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="Microsoft.SyndicationFeed.ReaderWriter" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Voidwell.DaybreakGames.CensusStore\Voidwell.DaybreakGames.CensusStore.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Data\Voidwell.DaybreakGames.Data.csproj" />
    <ProjectReference Include="..\Voidwell.DaybreakGames.Domain\Voidwell.DaybreakGames.Domain.csproj" />
  </ItemGroup>

</Project>
