name: build-and-test

on:
  pull_request:
    branches:
    - master
  workflow_call:
    
jobs:
  build-and-test:
      
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore dependencies
      env:
        NUGET_RESTORE_MSBUILD_ARGS: /p:Configuration=Release
      run: nuget restore

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal
