name: Deploy Release

on:
  push:
    branches:
    - master
    
jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  deploy-release:
    needs: [build-and-test]

    runs-on: ubuntu-latest

    steps:
    - name: Determine version number
      id: version
      shell: bash
      run: |
        if [ "${{ vars.BASE_VERSION_NUMBER }}" != '' ]; then
          echo "value=$((${{ vars.BASE_VERSION_NUMBER }} + ${{ github.run_number }}))" >> $GITHUB_OUTPUT;
        else
          echo "value=${{ github.run_number }}" >> $GITHUB_OUTPUT;
        fi

    - uses: actions/checkout@v2

    - name: Login to Voidwell Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
      
    - name: Publish
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_PROJECT }}/${{ vars.DOCKER_SERVICE }}:latest
          ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_PROJECT }}/${{ vars.DOCKER_SERVICE }}:${{ steps.version.outputs.value }}

    - name: Update release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'voidwell',
            repo: 'server',
            workflow_id: 'deploy-release.yml',
            ref: 'master',
            inputs: {
              project: ${{ vars.DOCKER_SERVICE }},
              version: ${{ steps.version.outputs.value }}
            }
          })
